### ISSUE TITLE
WP 5.9 & 2022 Theme = Fonts are incorrect on pages

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/post-and-page-builder#307]
WP 5.9 Beta 1
2022 Theme
Stable PPB
Chrome
Not CWP

On the Add Block screen, the fonts on the right are correct but when I add them to the page the fonts change. The fonts are incorrect in the editor but correct on the front-end.
![fonts-dont-match](https://user-images.githubusercontent.com/20601160/144243390-e3d17b1a-364f-40f1-bd9c-998ba783a256.PNG)

Editor / incorrect:
![editor](https://user-images.githubusercontent.com/20601160/144243404-45fe8ec0-9c78-4a88-97f4-64657b1b7e93.PNG)

Front-end / correct:
![front-end](https://user-images.githubusercontent.com/20601160/144243434-0da1190a-d60f-4ba3-b2af-049c67a16837.PNG)

**Comment by nicolepaschen** [comment]
See also https://github.com/BoldGrid/post-and-page-builder/issues/325

**Comment by jamesros161** [comment]
This is an inherent issue with compatibility between PPB and Block Themes ( which is what 2022 is ). PPB is designed to work with bootstrap based themes, not block themes. I think that since the number of users who use PPB with the default WP theme is likely very slim, this can be held off unless we get a significant amount of complaints. Most users will use PPB with Crio, V1 themes, or a 3rd party theme.
