### ISSUE TITLE
WP6.5 - AVIF image support - cannot crop AVIF images

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/post-and-page-builder#582]
WP 6.5 added support for AVIF images. I uploaded one to my install, used https://squoosh.app/ to create it. However I am unable to crop it as expected with the PPB tool. The cropping screen never gives me a success message and the image goes on the page uncropped. I get this console error:

![image](https://github.com/BoldGrid/post-and-page-builder/assets/20601160/6a9eb2db-af73-423a-b2ea-a91a596083f6)

**Comment by jamesros161** [comment]
This issue is a server configuration issue. The host server has to be configured with a version of libGD that supports avif editing. See the following tickets:
https://core.trac.wordpress.org/ticket/60628
https://github.com/php/php-src/issues/12019
https://bugs.launchpad.net/ubuntu/+source/libgd2/+bug/2031934#yui_3_10_3_1_1708785074264_150
