### ISSUE TITLE
Update get_boldgrid_theme_name to use Template instead of Text Domain

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/post-and-page-builder#79]
**Is your feature request related to a problem? Please describe.**
When creating a child theme of an existing BoldGrid Inspiration, the Post and Page Builder requires you to include 'boldgrid' in the Text Domain.

**Describe the solution you'd like**
Altering Line 75 of class-boldgrid-editor-theme.php from:
```strpos( $current_theme->get( 'TextDomain' ), 'boldgrid' ) !== false ) {```
to:
```strpos( $current_theme->get( 'Template' ), 'boldgrid' ) !== false ) {```
Resolves this issue for child themes.

**Describe alternatives you've considered**
Documentation has already been updated to reflect the need to specify a Text Domain containing the string "boldgrid" in child themes.
https://www.boldgrid.com/support/designers-developers/how-to-create-a-child-theme-to-customize-your-wordpress-website/

**Additional context**
This solution was proposed by a user here:
https://www.boldgrid.com/feedback/communities/20/topics/3397-why-are-post-and-page-builder-plugin-css-called-in-haven-child-theme

**Comment by timelsass** [comment]
Just some other notes:
- working with "prime" the text domain doesn't refer to "boldgrid" which has always been a thing that has been an annoyance.
- I think we should check the theme -> normalize "Author" and then check on that containing boldgrid
- This would free up theme names at least here from being tied to using a naming convention such as `boldgrid-{$name}`
- We could  then check if theme is a child theme, and then if it is check the Template for the parent theme slug, and then check the parent theme for the Author containing boldgrid.

**Comment by timelsass** [comment]
I sent in a PR with the logic stated above @jessecowens - I couldn't just change the check from `TextDomain` to `Template` because template is not in the style.css headers for parent themes, so that would be null when checking a parent theme.  I think this solution will work best to remove the need for prefixing with `boldgrid-`, so authors will be able to free up their theme name to whatever they want.  This also resolves the situation where https://github.com/boldgrid/prime is being used, and it's not prefixed by default, along with "Crio" for the wp.org theme when that time comes.

**Comment by rramo012** [comment]
This has issue has been deployed in v1.10.2
